name: Admin Tools
version: '${project.version}'
main: com.soychristian.admintools.AdminTools
api-version: 1.19
commands:
  admintools:
    description: Admin Tools
    usage: /admintools
    aliases: [at]

