name: AdminTools
version: '${project.version}'
main: com.soychristian.admintools.AdminTools
commands:
  admintools:
    description: Admin Tools
    usage: /admintools
    aliases: [at]
  listuseronline:
    description: List all users
    usage: /listuseronline
    aliases: [lu]
  listuseroffline:
    description: List all offline users
    usage: /listuseroffline
    aliases: [luo]

