name: AdminTools
version: '${project.version}'
main: com.soychristian.admintools.AdminTools
commands:
  admintools:
    description: Admin Tools
    usage: /admintools
    aliases: [at]
  listuser:
    description: List all users
    usage: /listuser
    aliases: [lu]

